ุงูุงุณู: GitHub Actions Demo
run-name: ${{ github.actor }} ูุฎุชุจุฑ GitHub Actions ๐
ุนูู: [ุฏูุน]
ุงููุธุงุฆู:
  ุงุณุชูุดุงู-GitHub-Actions:
    ูุนูู ุนูู: ubuntu-latest
    ุฎุทูุงุช:
      - ุชุดุบูู: echo "๐ ุชู ุชุดุบูู ุงููููุฉ ุชููุงุฆููุง ุจูุงุณุทุฉ ุญุฏุซ ${{ github.event_name }}."
      - ุชุดุบูู: echo "๐ง ูุชู ุชุดุบูู ูุฐู ุงููููุฉ ุงูุขู ุนูู ุฎุงุฏู ${{ runner.os }} ุงููุณุชุถุงู ุจูุงุณุทุฉ GitHub!"
      - ุชุดุบูู: echo "๐ ุงุณู ูุฑุนู ูู ${{ github.ref }} ููุณุชูุฏุนู ูู ${{ github.repository }}."
      - ุงูุงุณู: ุงูุชุญูู ูู ุฑูุฒ ุงููุณุชูุฏุน
        ุงูุงุณุชุฎุฏุงูุงุช: actions/checkout@v4
      - ุชุดุบูู: echo "๐ก ุชู ุงุณุชูุณุงุฎ ูุณุชูุฏุน ${{ github.repository }} ุฅูู ุงููุดุบู."
      - ุชุดุบูู: echo "๐ฅ๏ธ ุฃุตุจุญ ุณูุฑ ุงูุนูู ุฌุงูุฒูุง ุงูุขู ูุงุฎุชุจุงุฑ ุงูููุฏ ุงูุฎุงุต ุจู ุนูู ุงููุดุบู."
      - ุงูุงุณู: ูุงุฆูุฉ ุงููููุงุช ุงูููุฌูุฏุฉ ูู ุงููุณุชูุฏุน
        ุชุดุบูู: |
          ls ${{ github.workspace }}
      - ุชุดุบูู: echo "๐ ุญุงูุฉ ูุฐู ุงููุธููุฉ ูู ${{ job.status }}."
